import type { Metadata } from 'next';
import { Geist, Geist_Mono, Lato } from 'next/font/google';
import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
  preload: true,
  variable: '--font-lato-sans',
});

export const metadata: Metadata = {
  title: 'ConexMeet | Video Chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>{children}</body>
    </html>
  );
}
