import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import SessionProviderWrapper from './components/SessionProviderWrapper';
import { LanguageProvider } from './context/useLanguageContext';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'ConexMeet | Video Chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${poppins.variable} antialiased`}>
        <LanguageProvider>
          <SessionProviderWrapper>
            {children}
          </SessionProviderWrapper>
        </LanguageProvider>
      </body>
    </html>
  );
}
