import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
import SessionProviderWrapper from './components/SessionProviderWrapper';
import { LanguageProvider } from './context/useLanguageContext';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'ConexMeet | Video Chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head></head>
      <body className={`${poppins.variable} antialiased`}>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-YDKVM39PVG"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-YDKVM39PVG');
          `}
        </Script>

        <LanguageProvider>
          <SessionProviderWrapper>
            {children}
          </SessionProviderWrapper>
        </LanguageProvider>
      </body>
    </html>
  );
}
